[package]
name = "cupid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.16.0"

local-ip-address = "0.5.1"

const_format = "0.2.30"